# Generated by Django 6.0 on 2025-12-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
    ]
