# Generated by Django 6.0 on 2025-12-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_options_payment_checkout_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
    ]
