# Generated by Django 6.0 on 2025-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(editable=False, help_text='Unique payment reference', max_length=100, null=True, unique=True),
        ),
    ]
