# Generated by Django 6.0 on 2025-12-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_orders', to='cap.cap')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('shipping_address', models.TextField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('caps', models.ManyToManyField(related_name='orders', through='order.CapOrder', to='cap.cap')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
