# Generated by Django 6.0 on 2025-12-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('payment', '0002_remove_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='caporder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='payment.payment'),
            preserve_default=False,
        ),
    ]
