# Generated by Django 6.0 on 2025-12-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_caporder_price_order_payment'),
        ('payment', '0002_remove_payment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payment.payment'),
        ),
    ]
